config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
  }
  root to: 'pages#home'

  resources :tours
  resources :ratings, only: [ :new, :create, :show, :edit, :delete ]
  resources :tourpaintings
  resources :paintings
  resources :dashboards
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :tours do
    member do
      post 'publish', to: "tours#published"
    end
  end
end

app/models/painting.rb
class Painting < ApplicationRecord
  has_many :tour_paintings
  has_one_attached :photo
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController

  def index
  @paintings = Painting.all
  @user = current_user
  @tour = @user.tours.last
end

  def show
    @painting = Painting.find(params[:id])

    @user = current_user
    @tour = @user.tours.last

    @tour_painting = TourPainting.new
    @tour_painting.painting = @painting
    @tour_painting.tour = @tour

    @tour_painting.save!
    end
  end

app/views/paintings/index.html.erb
<%= link_to "Ajouter la vidéo de ma visite", edit_tour_path(@tour) %>


<% @paintings.each do |p| %>
  <div>
   <p><%= p.title %></p>
   <p><%= p.artist %></p>
   <%= cl_image_tag p.photo.key, height: 500, width: 600, crop: :fill %>
   <%= link_to "select", painting_path(p) %>
  </div>
<% end %>

app/views/paintings/show.html.erb
  <div>
    <%= cl_image_tag @painting.photo.key, height: 500, width: 600, crop: :fill %>
  </div>

<%= link_to "Ajouter à ma visite", paintings_path %>