config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
  }
  root to: 'pages#home'

  resources :tours
  resources :ratings, only: [ :new, :create, :show, :edit, :delete ]
  resources :tourpaintings
  resources :paintings
  resources :dashboards
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :tours do
    member do
      post 'publish', to: "tours#published"
    end
  end
end

app/models/tour.rb
class Tour < ApplicationRecord

  LANGUAGE = ['French 🇫🇷','English 🇬🇧', 'Spanish 🇪🇸']

  belongs_to :user
  has_many :tour_paintings
  has_many :ratings
  has_many :paintings, through: :tour_paintings
  has_one_attached :video
  has_one_attached :photo

  # validates :title, :description, presence: true
  # validates :title, uniqueness: true
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
    skip_before_action :authenticate_user!, only: :index

  def index
    @tours = Tour.all
  end

  def show
    @tour = Tour.find(params[:id])
    @user = current_user

    @first_painting = @tour.tour_paintings.first.painting
  end

  def edit
    @tour = Tour.find(params[:id])
  end

  def update
    @tour = Tour.find(params[:id])
    @tour.update(params_tour)

    # no need for app/views/restaurants/update.html.erb
    redirect_to tour_path(@tour)
  end

  def destroy
  end

  def new
    @tour = Tour.new
  end

  def create
    @tour = Tour.new(params_tour)
    @tour.user = current_user

    if @tour.save!

      redirect_to paintings_path
    else
      render :new
    end
  end

  def published
    @tour = Tour.find(params[:id])
    @tour.published = true
    @tour.save
    redirect_to dashboards_path
  end

private
  def params_tour
    params.require(:tour).permit(:title, :description, :languages, :painting_id, :tour_painting_id, :photo, :video)
  end
end

app/views/tours/edit.html.erb
<%= simple_form_for @tour, url: tour_path(@tour) do |f| %>
    <%= f.input :video, as: :file %>

      <div class="form-actions">
        <%= f.button :submit, "Ajouter la vidéo de ma visite" %>
      </div>
    <% end %>

<%= link_to "back to paintings", paintings_path %>

app/views/tours/index.html.erb
<h1>This is all the tours </h1>

<div class="main-container">
  <div class="container">
    <div class="row lg-10">
      <div class="card bg-dark text-white">
        <img class="card-img" src="https://source.unsplash.com/random" alt="Card image" style="height: 100%; width: 100%; object-fit: contain"/>
        <div class="card-img-overlay">
          <h5> <%= @tours.first.title %></h5>
          <p> <%= @tours.first.description %></p>
        </div>
      </div>
    </div>

    <div class="row lg-10">
      <div class="cards">
            <% @tours.each do |tour| %>
              <% if tour.published? %>
                <div class="recommendations" style="background-image: url('https://source.unsplash.com/random');"/>
                    <div class="description">
                      <p><%= tour.title %></p>
                      <p> <%= tour.description %></p>
                      <p> <%= link_to "See more", tour_path(tour) %></p>
                    </div>
                </div>
              <% end %>
            <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tours/new.html.erb
<h1> create a new tour </h1>

<%= simple_form_for @tour, url: tours_path do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :languages, collection: Tour::LANGUAGE %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/tours/show.html.erb
<div class="container">
  <div class="row">
    <div class="col col-lg-9">
        <h1><%= @tour.title %></h1>
        <p><%= @tour.description %></p>
        <p><%= @tour.duration %> mins </p>
          <%= cl_video_tag(@tour.video.key, :width => 600, :height => 500, :crop => :crop,
          :loop => false, :autoplay => true, :poster => false, :controls => true,
          :fallback_content => "Your browser does not support HTML5 video tags"  ) %>

<div id="carouselExampleControls" class="carousel slide" data-interval="false">
          <div class="carousel-inner">
            <div class="carousel-item active" >
              <%= cl_image_tag @first_painting.photo.key, height: 500, width: 855, crop: :fill %>
            </div>

          <% @tour.paintings.drop(1).each do |painting| %>
            <div class="carousel-item">
              <%= cl_image_tag painting.photo.key, height: 500, width: 855, crop: :fill %>
              <div>
              </div>
            </div>
           <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
    <div class="col col-lg-3">
      <div class="guide profil">
        <h3> <%= @tour.user.first_name %> <%= @tour.user.last_name %></h3>
        <p> <%= @tour.user.description %> </p>
      </div>
      <div>
    </div>
  </div>
  </div>
  <div class="row">
    <div class="col">
      <% @tour.paintings.each do |painting| %>
      <%= cl_image_tag painting.photo.key, height: 150, width: 200, crop: :fill  %>
      <% end %>
    </div>
  </div>
</div>
<p> <%= link_to "Sign-out", destroy_user_session_path, method: :delete %></p>

<p><%= link_to "Edit tour", paintings_path %></p>

<p> <%= link_to "Publish tour", publish_tour_path(@tour), method: :post %></p>